version: '3.3'

services:

  server:
    restart: always
    build:
      context: ./
      dockerfile: stripe_test/Dockerfile
    ports:
      - '8000:8000'
    command: gunicorn stripe_test.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    restart: always
    image: postgres:12.4-alpine
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file:
      - ./.env