# Generated by Django 4.1.1 on 2022-09-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'US dollars'), ('rub', 'RF rubles')], default='rub', max_length=3),
            preserve_default=False,
        ),
    ]
