# Generated by Django 4.1.1 on 2022-09-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_price_alter_order_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
