# Generated by Django 4.1.1 on 2022-09-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_item_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
