# Generated by Django 4.1.1 on 2022-09-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.RemoveField(
            model_name='discount',
            name='currency',
        ),
    ]
